elasticsearch:
  image: dcrbsltd/elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - 9200:9200
    - 9300:9300

kibana:
  image: dcrbsltd/kibana:latest
  links:
    - elasticsearch
  ports:
    - 5601:5601

logstash:
  image: dcrbsltd/logstash:latest
  command: logstash -f /etc/logstash.conf
  ports:
    - 5000:5000
  links:
    - elasticsearch
    - redis

redis:
  image: dcrbsltd/redis:latest
  ports:
    - 6379:6379
