FROM logstash:5
MAINTAINER David Reay <david@dcrbsltd.com>

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json 

COPY logstash.conf /etc/logstash.conf

